version: '3.8'

services:
  mysql:
    image: 'mysql:latest'
    environment:
      - MYSQL_DATABASE=User
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=carlos
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  java-app: 
    build: .
    ports:
      - "8080:8080" 
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/User?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=carlos
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge